name: Deploy to Neocities

on:
  push:
    branches:
      - main  # 如果你的默认分支是 master，请改成 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to Neocities
        uses: bcomnes/deploy-neocities@v1
        with:
          api_key: ${{ secrets.NEOCITIES_KEY }}
